---
title: "Likert"
output: html_document
date: '2024-10-12'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
```

```{r}
setwd("D:/cfs")
```


```{r}
data = read_excel("./Data/23-24 CFSN Student Feedback Survey + Mentor Assistance (Responses).xlsx")
```

Reading multiple sheets in the Excel

```{r}
multiplesheets <- function(fname) { 
   
  # getting info about all excel sheets 
  sheets <- readxl::excel_sheets(fname) 
  tibble <- lapply(sheets, function(x) readxl::read_excel(fname, sheet = x)) 
  data_frame <- lapply(tibble, as.data.frame) 
    
  # assigning names to data frames 
  # names(data_frame) <- sheets 
    
  # print data frame 
  # print(data_frame) 
} 
```


```{r}
data = multiplesheets("./Data/23-24 CFSN Student Feedback Survey + Mentor Assistance (Responses).xlsx")
```

Each sheet is in a list of data. 

Example 

```{r}
data[[1]]
```

```{r}
data[[2]]
```
Make a summary frequency table for each column from Q to AB (17 to 28). 

```{r}
for (column_index in 17:28){
  likert = unlist(lapply(data, function(df) df[column_index]))
  print(colnames(data[[1]])[column_index])
  col_name = colnames(data[[1]])[column_index]
  freq_table = table(likert)
  print(freq_table)
}
```

Making barplots of histogram for each category of response. 

```{r}
for (column_index in 17:19){
  likert = unlist(lapply(data, function(df) df[column_index]))
  print(colnames(data[[1]])[column_index])
  print(table(likert))
  
  # Get the column name
  col_name <- colnames(data[[1]])[column_index]
  
  # Extract the text inside square brackets
  title_text <- sub(".*\\[(.*)\\].*", "\\1", col_name)
  
  # Set factor levels to include all response options from 1 to 5
  likert <- factor(likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
  
  # Create a frequency table and convert to percentages
  freq_table <- table(likert)
  percent_table <- (freq_table / sum(freq_table)) * 100
  
  # Save the figure
  # file_name = paste0(column_index, '_', title_text, 'png')
  # png(file_name, width = 800, height = 600)
  
  
  # Create the percent bar plot with all categories
  barplot(
    percent_table, 
    main = title_text, 
    xlab = 'Response', 
    ylab = 'Percentage (%)', 
    ylim = c(0, 100),  # Set y-axis limit to 100%
    names.arg = c('Strongly Disagree',  'Disagree', 'Neutral', 'Agree', 'Strongly Agree'),   # Ensure x-axis shows all options 1-5
    col = 'lightblue' 
  )
  
  # dev.off()
}
```

Making barplots after grouping. 

```{r}
for (column_index in 17:19){
  likert = unlist(lapply(data, function(df) df[column_index]))
  print(colnames(data[[1]])[column_index])
  print(table(likert))
  
  # Get the column name
  col_name <- colnames(data[[1]])[column_index]
  
  # Extract the text inside square brackets
  title_text <- sub(".*\\[(.*)\\].*", "\\1", col_name)
  
  # Set factor levels to include all response options from 1 to 5
  likert <- factor(likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
  
  # Create a frequency table and convert to percentages
  freq_table <- table(likert)
  percent_table <- (freq_table / sum(freq_table)) * 100
  
  percent_table_grouped = c(percent_table[1] + percent_table[2], percent_table[3], percent_table[4] + percent_table[5])
  
  # Save the figure
  file_name = paste0(column_index, '_grouped_', title_text, 'png')
  # png(file_name, width = 800, height = 600)
  
  
  # Create the percent bar plot with all categories
  barplot(
    percent_table_grouped, 
    main = title_text, 
    xlab = 'Response', 
    ylab = 'Percentage (%)', 
    ylim = c(0, 100),  # Set y-axis limit to 100%
    names.arg = c('Strongly Disagree or Disagree', 'Neutral', 'Agree or Strongly Agree'),   # Ensure x-axis shows all options 1-5
    col = 'lightblue' 
  )
  
  # dev.off()
}
```

Table of agree or strongly agree

Mentee: 

```{r}
for (column_index in 17:28){
  likert = unlist(lapply(data, function(df) df[column_index]))
  print(colnames(data[[1]])[column_index])
  # print(table(likert))
  
  # Get the column name
  col_name <- colnames(data[[1]])[column_index]
  
  # Extract the text inside square brackets
  title_text <- sub(".*\\[(.*)\\].*", "\\1", col_name)
  
  # Set factor levels to include all response options from 1 to 5
  likert <- factor(likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
  
  # Create a frequency table and convert to percentages
  freq_table <- table(likert)
  percent_table <- (freq_table / sum(freq_table)) * 100
  
  percent_table_grouped = c(percent_table[1] + percent_table[2], percent_table[3], percent_table[4] + percent_table[5])
  
  print(percent_table_grouped)
}
```

Mentor: 

```{r}
mentor = multiplesheets("./Data/CFSN Mentor Feedback Survey 23-24 (Responses).xlsx")
```

```{r}
for (column_index in 4:14){
  likert = unlist(lapply(mentor, function(df) df[column_index]))
  print(colnames(mentor[[1]])[column_index])
  # print(table(likert))
  
  # Get the column name
  col_name <- colnames(mentor[[1]])[column_index]
  
  # Extract the text inside square brackets
  title_text <- sub(".*\\[(.*)\\].*", "\\1", col_name)
  
  # Set factor levels to include all response options from 1 to 5
  likert <- factor(likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
  
  # Create a frequency table and convert to percentages
  freq_table <- table(likert)
  percent_table <- (freq_table / sum(freq_table)) * 100
  
  percent_table_grouped = c(percent_table[1] + percent_table[2], percent_table[3], percent_table[4] + percent_table[5])
  
  print(percent_table_grouped)
}
```

family 

```{r}
family  = multiplesheets("./Data/CFSN Family Feedback Survey 23-24 (Responses).xlsx")
```
```{r}
for (column_index in 6:14){
  likert = unlist(lapply(family, function(df) df[column_index]))
  print(colnames(family[[1]])[column_index])
  # print(table(likert))
  
  print(table(likert))
  

  # Get the column name
  col_name <- colnames(family[[1]])[column_index]

  # Extract the text inside square brackets
  title_text <- sub(".*\\[(.*)\\].*", "\\1", col_name)

  # Set factor levels to include all response options from 1 to 5
  likert <- factor(likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Estar de acuerdo', '4 - Agree', '5 - Totalmente de acuerdo', '5 - Strongly Agree'))

  # Create a frequency table and convert to percentages
  freq_table <- table(likert)
  percent_table <- (freq_table / sum(freq_table)) * 100

  percent_table_grouped = c(percent_table[1] + percent_table[2], percent_table[3], percent_table[4] + percent_table[5] + percent_table[6] + percent_table[7])

  print(percent_table_grouped)
}
```

Partner

```{r}
partner  = multiplesheets("./Data/CFSN Partner Survey (Responses) (2022 and 2024).xlsx")
```

```{r}
for (column_index in 7:13){
  likert = unlist(lapply(partner, function(df) df[column_index]))
  print(colnames(partner[[1]])[column_index])
  # print(table(likert))
  
  # Get the column name
  col_name <- colnames(partner[[1]])[column_index]
  
  # Extract the text inside square brackets
  title_text <- sub(".*\\[(.*)\\].*", "\\1", col_name)
  
  # Set factor levels to include all response options from 1 to 5
  likert <- factor(likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
  
  # Create a frequency table and convert to percentages
  freq_table <- table(likert)
  percent_table <- (freq_table / sum(freq_table)) * 100
  
  percent_table_grouped = c(percent_table[1] + percent_table[2], percent_table[3], percent_table[4] + percent_table[5])
  
  print(percent_table_grouped)
}
```

