---
title: "Untitled"
output: html_document
date: '2024-11-03'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readxl)
```

```{r}
library(dplyr)
library(ggplot2)
```


```{r}
setwd("D:/cfs")
```


```{r}
mentee = read_excel("./Data/23-24 CFSN Student Feedback Survey + Mentor Assistance (Responses).xlsx")
mentor = read_excel("./Data/CFSN Mentor Feedback Survey 23-24 (Responses).xlsx")
```

Reading multiple sheets in the Excel

```{r}
multiplesheets <- function(fname) { 
   
  # getting info about all excel sheets 
  sheets <- readxl::excel_sheets(fname) 
  tibble <- lapply(sheets, function(x) readxl::read_excel(fname, sheet = x)) 
  data_frame <- lapply(tibble, as.data.frame) 
    
  # assigning names to data frames 
  # names(data_frame) <- sheets 
    
  # print data frame 
  # print(data_frame) 
} 
```


```{r}
mentee = multiplesheets("./Data/23-24 CFSN Student Feedback Survey + Mentor Assistance (Responses).xlsx")
mentor = multiplesheets("./Data/CFSN Mentor Feedback Survey 23-24 (Responses).xlsx")
```

```{r}
colnames(mentee[[1]])
```

Improve: 17, 4

Confidence: 18, 5

Enjoy: 21, 13

Voice and respect: 23, 12

```{r}
colnames(mentor[[1]])
```

```{r}
mentee_index = 17 
mentee_likert = unlist(lapply(mentee, function(df) df[mentee_index]))
likert <- factor(mentee_likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
mentee_freq_table = table(likert)
mentee_percent_table = mentee_freq_table/sum(mentee_freq_table) * 100
print(mentee_percent_table)

mentor_index = 4
mentor_likert = unlist(lapply(mentor, function(df) df[mentor_index]))
likert <- factor(mentor_likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
mentor_freq_table = table(likert)
mentor_percent_table = mentor_freq_table/sum(mentor_freq_table) * 100
print(mentor_percent_table)
```

```{r}
response = rep(c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'), 2)
role = rep(c("Mentee", "Mentor"), each = length(mentor_percent_table))
data = data.frame(Percent = c(as.numeric(mentee_percent_table), as.numeric(mentor_percent_table)), Response = response, Role = role)
data
```

```{r}
ggplot(data, aes(x = Response, y = Percent, fill = Role)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  labs(
    title = "I (My mentee) have improved reading skills",
    x = "Response",
    y = "Percentage"
  ) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
data_grouped <- data %>%
  mutate(
    GroupedResponse = case_when(
      Response %in% c("5 - Strongly Agree", "4 - Agree") ~ "Agree/Strongly Agree",
      Response %in% c("1 - Strongly Disagree", "2 - Disagree") ~ "Disagree/Strongly Disagree",
      TRUE ~ "Neutral"
    )
  ) %>% group_by(Role, GroupedResponse) %>%
  summarize(Percent = sum(Percent))
  # Summarize the percentages for the grouped responses
  
```

```{r}
data_grouped
```

```{r}
data_grouped$GroupedResponse <- factor(
  data_grouped$GroupedResponse,
  levels = c("Disagree/Strongly Disagree", "Neutral", "Agree/Strongly Agree")
)
```


```{r}
# png("Comparison_improved_reading_skills.png")
ggplot(data_grouped, aes(x = GroupedResponse, y = Percent, fill = Role)) +
  geom_bar(stat = "identity", position = position_dodge()) + ylim(0, 100) + 
  geom_text(
    aes(label = paste0(round(Percent, 2), "%")),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
    title = "I have improved reading skills / My mentee has improved reading skills",
    x = "Response",
    y = "Percentage"
  ) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") # +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1))
# dev.off()
```

#### Confidence 

```{r}
mentee_index = 18 
mentee_likert = unlist(lapply(mentee, function(df) df[mentee_index]))
likert <- factor(mentee_likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
mentee_freq_table = table(likert)
mentee_percent_table = mentee_freq_table/sum(mentee_freq_table) * 100
print(mentee_percent_table)

mentor_index = 5
mentor_likert = unlist(lapply(mentor, function(df) df[mentor_index]))
likert <- factor(mentor_likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
mentor_freq_table = table(likert)
mentor_percent_table = mentor_freq_table/sum(mentor_freq_table) * 100
print(mentor_percent_table)
```

```{r}
response = rep(c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'), 2)
role = rep(c("Mentee", "Mentor"), each = length(mentor_percent_table))
data = data.frame(Percent = c(as.numeric(mentee_percent_table), as.numeric(mentor_percent_table)), Response = response, Role = role)
data
```

```{r}
data_grouped <- data %>%
  mutate(
    GroupedResponse = case_when(
      Response %in% c("5 - Strongly Agree", "4 - Agree") ~ "Agree/Strongly Agree",
      Response %in% c("1 - Strongly Disagree", "2 - Disagree") ~ "Disagree/Strongly Disagree",
      TRUE ~ "Neutral"
    )
  ) %>% group_by(Role, GroupedResponse) %>%
  summarize(Percent = sum(Percent))
  # Summarize the percentages for the grouped responses
  
```

```{r}
data_grouped
```

```{r}
data_grouped$GroupedResponse <- factor(
  data_grouped$GroupedResponse,
  levels = c("Disagree/Strongly Disagree", "Neutral", "Agree/Strongly Agree")
)
```


```{r}
# png("Comparison_more_confident.png")
ggplot(data_grouped, aes(x = GroupedResponse, y = Percent, fill = Role)) +
  geom_bar(stat = "identity", position = position_dodge()) + ylim(0, 100) + 
  geom_text(
    aes(label = paste0(round(Percent, 2), "%")),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
    title = "I feel more confident / My mentee feel more confident",
    x = "Response",
    y = "Percentage"
  ) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") # +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1))
# dev.off()
```

#### Enjoy

```{r}
mentee_index = 21 
mentee_likert = unlist(lapply(mentee, function(df) df[mentee_index]))
likert <- factor(mentee_likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
mentee_freq_table = table(likert)
mentee_percent_table = mentee_freq_table/sum(mentee_freq_table) * 100
print(mentee_percent_table)

mentor_index = 13
mentor_likert = unlist(lapply(mentor, function(df) df[mentor_index]))
likert <- factor(mentor_likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
mentor_freq_table = table(likert)
mentor_percent_table = mentor_freq_table/sum(mentor_freq_table) * 100
print(mentor_percent_table)
```

```{r}
response = rep(c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'), 2)
role = rep(c("Mentee", "Mentor"), each = length(mentor_percent_table))
data = data.frame(Percent = c(as.numeric(mentee_percent_table), as.numeric(mentor_percent_table)), Response = response, Role = role)
data
```

```{r}
data_grouped <- data %>%
  mutate(
    GroupedResponse = case_when(
      Response %in% c("5 - Strongly Agree", "4 - Agree") ~ "Agree/Strongly Agree",
      Response %in% c("1 - Strongly Disagree", "2 - Disagree") ~ "Disagree/Strongly Disagree",
      TRUE ~ "Neutral"
    )
  ) %>% group_by(Role, GroupedResponse) %>%
  summarize(Percent = sum(Percent))
  # Summarize the percentages for the grouped responses
  
```

```{r}
data_grouped
```

```{r}
data_grouped$GroupedResponse <- factor(
  data_grouped$GroupedResponse,
  levels = c("Disagree/Strongly Disagree", "Neutral", "Agree/Strongly Agree")
)
```


```{r}
# png("Comparison_enjoy_session.png")
ggplot(data_grouped, aes(x = GroupedResponse, y = Percent, fill = Role)) +
  geom_bar(stat = "identity", position = position_dodge()) + ylim(0, 100) + 
  geom_text(
    aes(label = paste0(round(Percent, 2), "%")),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
    title = "I enjoy my mentoring sessions",
    x = "Response",
    y = "Percentage"
  ) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") # +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1))
# dev.off()
```

#### Value

```{r}
mentee_index = 23 
mentee_likert = unlist(lapply(mentee, function(df) df[mentee_index]))
likert <- factor(mentee_likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
mentee_freq_table = table(likert)
mentee_percent_table = mentee_freq_table/sum(mentee_freq_table) * 100
print(mentee_percent_table)

mentor_index = 12
mentor_likert = unlist(lapply(mentor, function(df) df[mentor_index]))
likert <- factor(mentor_likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
mentor_freq_table = table(likert)
mentor_percent_table = mentor_freq_table/sum(mentor_freq_table) * 100
print(mentor_percent_table)
```

```{r}
response = rep(c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'), 2)
role = rep(c("Mentee", "Mentor"), each = length(mentor_percent_table))
data = data.frame(Percent = c(as.numeric(mentee_percent_table), as.numeric(mentor_percent_table)), Response = response, Role = role)
data
```

```{r}
data_grouped <- data %>%
  mutate(
    GroupedResponse = case_when(
      Response %in% c("5 - Strongly Agree", "4 - Agree") ~ "Agree/Strongly Agree",
      Response %in% c("1 - Strongly Disagree", "2 - Disagree") ~ "Disagree/Strongly Disagree",
      TRUE ~ "Neutral"
    )
  ) %>% group_by(Role, GroupedResponse) %>%
  summarize(Percent = sum(Percent))
  # Summarize the percentages for the grouped responses
  
```

```{r}
data_grouped
```

```{r}
data_grouped$GroupedResponse <- factor(
  data_grouped$GroupedResponse,
  levels = c("Disagree/Strongly Disagree", "Neutral", "Agree/Strongly Agree")
)
```


```{r}
# png("Comparison_voice_value.png")
ggplot(data_grouped, aes(x = GroupedResponse, y = Percent, fill = Role)) +
  geom_bar(stat = "identity", position = position_dodge()) + ylim(0, 100) + 
  geom_text(
    aes(label = paste0(round(Percent, 2), "%")),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
    title = "My voice is important / I value my mentee's voice",
    x = "Response",
    y = "Percentage"
  ) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") # +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1))
# dev.off()
```


#### Family

```{r}
family  = multiplesheets("./Data/CFSN Family Feedback Survey 23-24 (Responses).xlsx")
```

```{r}
for (column in 6:14){
  print(colnames(family[[1]])[column])
  for(i in 1:length(family)){
    if(i == 1){
      df = family[[i]] 
      combined = ifelse(!is.na(df[[column]]), df[[column]], df[[column + 24]])
    }
    df = family[[i]]
    if(length(df) == 52){
      combined = c(combined, df[[column]])
    }
  
    if(length(df) == 26){
      combined = c(combined, df[[column - 2]])
    }  
    
  }
  
# Set factor levels to include all response options from 1 to 5
  likert <- factor(combined, levels = c('1 - Strongly Disagree', '1 - Muy en desacuerdo',  '3 - Neutral', '4 - Agree', '4 - Estar de acuerdo', '5 - Strongly Agree', '5 - Totalmente de acuerdo'))
  
  # Create a frequency table and convert to percentages
  freq_table <- table(likert)
  
  percent_table <- (freq_table / sum(freq_table)) * 100
  
  percent_table_grouped = c(percent_table[1] + percent_table[2], percent_table[3] , percent_table[4] + percent_table[5] + percent_table[6] + percent_table[7])
  
  print(percent_table_grouped)
  
}
```

```{r}
mentee_index = 17 
mentee_likert = unlist(lapply(mentee, function(df) df[mentee_index]))
likert <- factor(mentee_likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
mentee_freq_table = table(likert)
mentee_percent_table = mentee_freq_table/sum(mentee_freq_table) * 100
print(mentee_percent_table)

mentor_index = 4
mentor_likert = unlist(lapply(mentor, function(df) df[mentor_index]))
likert <- factor(mentor_likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
mentor_freq_table = table(likert)
mentor_percent_table = mentor_freq_table/sum(mentor_freq_table) * 100
print(mentor_percent_table)
```

```{r}
response = rep(c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'), 2)
role = rep(c("Mentee", "Mentor"), each = length(mentor_percent_table))
data = data.frame(Percent = c(as.numeric(mentee_percent_table), as.numeric(mentor_percent_table)), Response = response, Role = role)
data
```

```{r}
data_grouped <- data %>%
  mutate(
    GroupedResponse = case_when(
      Response %in% c("5 - Strongly Agree", "4 - Agree") ~ "Agree/Strongly Agree",
      Response %in% c("1 - Strongly Disagree", "2 - Disagree") ~ "Disagree/Strongly Disagree",
      TRUE ~ "Neutral"
    )
  ) %>% group_by(Role, GroupedResponse) %>%
  summarize(Percent = sum(Percent))
  # Summarize the percentages for the grouped responses
  
```

```{r}
data_grouped
```

```{r}
column = 6
for(i in 1:length(family)){
    if(i == 1){
      df = family[[i]] 
      combined = ifelse(!is.na(df[[column]]), df[[column]], df[[column + 24]])
    }
    df = family[[i]]
    if(length(df) == 52){
      combined = c(combined, df[[column]])
    }
  
    if(length(df) == 26){
      combined = c(combined, df[[column - 2]])
    }  
    
  }
  
# Set factor levels to include all response options from 1 to 5
  likert <- factor(combined, levels = c('1 - Strongly Disagree', '1 - Muy en desacuerdo',  '3 - Neutral', '4 - Agree', '4 - Estar de acuerdo', '5 - Strongly Agree', '5 - Totalmente de acuerdo'))
  
  # Create a frequency table and convert to percentages
  freq_table <- table(likert)
  
  percent_table <- (freq_table / sum(freq_table)) * 100
  
  percent_table_grouped = c(percent_table[1] + percent_table[2], percent_table[3] , percent_table[4] + percent_table[5] + percent_table[6] + percent_table[7])
  
  print(percent_table_grouped)
```


```{r}
data_grouped$GroupedResponse <- factor(
  data_grouped$GroupedResponse,
  levels = c("Disagree/Strongly Disagree", "Neutral", "Agree/Strongly Agree")
)
```


```{r}
response = c('Disagree/Strongly Disagree', 'Neutral', 'Agree/Strongly Agree')
role = rep("Family", 3)
data_family = data.frame(Percent = c(as.numeric(percent_table_grouped)), GroupedResponse = response, Role = role)
data_family
```

```{r}
data_all = bind_rows(data_grouped, data_family)
data_all
```

```{r}
data_all$GroupedResponse <- factor(
  data_all$GroupedResponse,
  levels = c("Disagree/Strongly Disagree", "Neutral", "Agree/Strongly Agree")
)
```

```{r}
colnames(mentor[[1]])
```

```{r}
colnames(mentee[[1]])
```

```{r}
colnames(family[[1]])
```

```{r}
data_all$Role <- factor(
  data_all$Role,
  levels = c("Mentee", "Mentor", "Family")
)
```


```{r}
# png("Comparison_improve_session_all.png")
ggplot(data_all, aes(x = GroupedResponse, y = Percent, fill = Role)) +
  geom_bar(stat = "identity", position = position_dodge()) + ylim(0, 100) + 
  geom_text(
    aes(label = paste0(round(Percent, 1), "%")),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
    title = "Perceptions of the Mentees' Reading Skills Improvement", # I enjoy my mentoring sessions/I enjoy my mentoring sessions/ \n My child enjoys their mentoring sessions
    x = "Response",
    y = "Percentage"
  ) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") # +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1))
# dev.off()
```

#### Value all

```{r}
mentee_index = 23 
mentee_likert = unlist(lapply(mentee, function(df) df[mentee_index]))
likert <- factor(mentee_likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
mentee_freq_table = table(likert)
mentee_percent_table = mentee_freq_table/sum(mentee_freq_table) * 100
print(mentee_percent_table)

mentor_index = 12
mentor_likert = unlist(lapply(mentor, function(df) df[mentor_index]))
likert <- factor(mentor_likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
mentor_freq_table = table(likert)
mentor_percent_table = mentor_freq_table/sum(mentor_freq_table) * 100
print(mentor_percent_table)
```

```{r}
response = rep(c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'), 2)
role = rep(c("Mentee", "Mentor"), each = length(mentor_percent_table))
data = data.frame(Percent = c(as.numeric(mentee_percent_table), as.numeric(mentor_percent_table)), Response = response, Role = role)
data
```

```{r}
data_grouped <- data %>%
  mutate(
    GroupedResponse = case_when(
      Response %in% c("5 - Strongly Agree", "4 - Agree") ~ "Agree/Strongly Agree",
      Response %in% c("1 - Strongly Disagree", "2 - Disagree") ~ "Disagree/Strongly Disagree",
      TRUE ~ "Neutral"
    )
  ) %>% group_by(Role, GroupedResponse) %>%
  summarize(Percent = sum(Percent))
  # Summarize the percentages for the grouped responses
  
```

```{r}
column = 14
for(i in 1:length(family)){
    if(i == 1){
      df = family[[i]] 
      combined = ifelse(!is.na(df[[column]]), df[[column]], df[[column + 24]])
    }
    df = family[[i]]
    if(length(df) == 52){
      combined = c(combined, df[[column]])
    }
  
    if(length(df) == 26){
      combined = c(combined, df[[column - 2]])
    }  
    
  }
  
# Set factor levels to include all response options from 1 to 5
  likert <- factor(combined, levels = c('1 - Strongly Disagree', '1 - Muy en desacuerdo',  '3 - Neutral', '4 - Agree', '4 - Estar de acuerdo', '5 - Strongly Agree', '5 - Totalmente de acuerdo'))
  
  # Create a frequency table and convert to percentages
  freq_table <- table(likert)
  
  percent_table <- (freq_table / sum(freq_table)) * 100
  
  percent_table_grouped = c(percent_table[1] + percent_table[2], percent_table[3] , percent_table[4] + percent_table[5] + percent_table[6] + percent_table[7])
  
  print(percent_table_grouped)
```

```{r}
response = c('Disagree/Strongly Disagree', 'Neutral', 'Agree/Strongly Agree')
role = rep("Family", 3)
data_family = data.frame(Percent = c(as.numeric(percent_table_grouped)), GroupedResponse = response, Role = role)
data_family
```

```{r}
data_all = bind_rows(data_grouped, data_family)
data_all
```

```{r}
data_all$GroupedResponse <- factor(
  data_all$GroupedResponse,
  levels = c("Disagree/Strongly Disagree", "Neutral", "Agree/Strongly Agree")
)
```

```{r}
data_all$Role <- factor(
  data_all$Role,
  levels = c("Mentee", "Mentor", "Family")
)
```



```{r}
# png("Comparison_value_session_all.png")
ggplot(data_all, aes(x = GroupedResponse, y = Percent, fill = Role)) +
  geom_bar(stat = "identity", position = position_dodge()) + ylim(0, 100) + 
  geom_text(
    aes(label = paste0(round(Percent, 1), "%")),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
    title = "Perceptions of the Mentees' Voices Being Valued", # I enjoy my mentoring sessions/I enjoy my mentoring sessions/ \n My child enjoys their mentoring sessions
    x = "Response",
    y = "Percentage"
  ) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") # +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1))
# dev.off()
```

#### Enjoy all

```{r}
mentee_index = 21 
mentee_likert = unlist(lapply(mentee, function(df) df[mentee_index]))
likert <- factor(mentee_likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
mentee_freq_table = table(likert)
mentee_percent_table = mentee_freq_table/sum(mentee_freq_table) * 100
print(mentee_percent_table)

mentor_index = 13
mentor_likert = unlist(lapply(mentor, function(df) df[mentor_index]))
likert <- factor(mentor_likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
mentor_freq_table = table(likert)
mentor_percent_table = mentor_freq_table/sum(mentor_freq_table) * 100
print(mentor_percent_table)
```

```{r}
response = rep(c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'), 2)
role = rep(c("Mentee", "Mentor"), each = length(mentor_percent_table))
data = data.frame(Percent = c(as.numeric(mentee_percent_table), as.numeric(mentor_percent_table)), Response = response, Role = role)
data
```

```{r}
data_grouped <- data %>%
  mutate(
    GroupedResponse = case_when(
      Response %in% c("5 - Strongly Agree", "4 - Agree") ~ "Agree/Strongly Agree",
      Response %in% c("1 - Strongly Disagree", "2 - Disagree") ~ "Disagree/Strongly Disagree",
      TRUE ~ "Neutral"
    )
  ) %>% group_by(Role, GroupedResponse) %>%
  summarize(Percent = sum(Percent))
  # Summarize the percentages for the grouped responses
  
```

```{r}
column = 13
for(i in 1:length(family)){
    if(i == 1){
      df = family[[i]] 
      combined = ifelse(!is.na(df[[column]]), df[[column]], df[[column + 24]])
    }
    df = family[[i]]
    if(length(df) == 52){
      combined = c(combined, df[[column]])
    }
  
    if(length(df) == 26){
      combined = c(combined, df[[column - 2]])
    }  
    
  }
  
# Set factor levels to include all response options from 1 to 5
  likert <- factor(combined, levels = c('1 - Strongly Disagree', '1 - Muy en desacuerdo',  '3 - Neutral', '4 - Agree', '4 - Estar de acuerdo', '5 - Strongly Agree', '5 - Totalmente de acuerdo'))
  
  # Create a frequency table and convert to percentages
  freq_table <- table(likert)
  
  percent_table <- (freq_table / sum(freq_table)) * 100
  
  percent_table_grouped = c(percent_table[1] + percent_table[2], percent_table[3] , percent_table[4] + percent_table[5] + percent_table[6] + percent_table[7])
  
  print(percent_table_grouped)
```

```{r}
response = c('Disagree/Strongly Disagree', 'Neutral', 'Agree/Strongly Agree')
role = rep("Family", 3)
data_family = data.frame(Percent = c(as.numeric(percent_table_grouped)), GroupedResponse = response, Role = role)
data_family
```

```{r}
data_all = bind_rows(data_grouped, data_family)
data_all
```

```{r}
data_all$GroupedResponse <- factor(
  data_all$GroupedResponse,
  levels = c("Disagree/Strongly Disagree", "Neutral", "Agree/Strongly Agree")
)
```

```{r}
data_all$Role <- factor(
  data_all$Role,
  levels = c("Mentee", "Mentor", "Family")
)
```



```{r}
# png("Comparison_enjoy_session_all.png")
ggplot(data_all, aes(x = GroupedResponse, y = Percent, fill = Role)) +
  geom_bar(stat = "identity", position = position_dodge()) + ylim(0, 100) + 
  geom_text(
    aes(label = paste0(round(Percent, 1), "%")),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
    title = "Perceptions of Enjoyment in Mentoring Sessions", # I enjoy my mentoring sessions/I enjoy my mentoring sessions/ \n My child enjoys their mentoring sessions
    x = "Response",
    y = "Percentage"
  ) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") # +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1))
# dev.off()
```

#### Recommend all

```{r}
mentee_index = 24 
mentee_likert = unlist(lapply(mentee, function(df) df[mentee_index]))
likert <- factor(mentee_likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
mentee_freq_table = table(likert)
mentee_percent_table = mentee_freq_table/sum(mentee_freq_table) * 100
print(mentee_percent_table)

mentor_index = 11
mentor_likert = unlist(lapply(mentor, function(df) df[mentor_index]))
likert <- factor(mentor_likert, levels = c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'))
mentor_freq_table = table(likert)
mentor_percent_table = mentor_freq_table/sum(mentor_freq_table) * 100
print(mentor_percent_table)
```

```{r}
response = rep(c('1 - Strongly Disagree',  '2 - Disagree', '3 - Neutral', '4 - Agree', '5 - Strongly Agree'), 2)
role = rep(c("Mentee", "Mentor"), each = length(mentor_percent_table))
data = data.frame(Percent = c(as.numeric(mentee_percent_table), as.numeric(mentor_percent_table)), Response = response, Role = role)
data
```

```{r}
data_grouped <- data %>%
  mutate(
    GroupedResponse = case_when(
      Response %in% c("5 - Strongly Agree", "4 - Agree") ~ "Agree/Strongly Agree",
      Response %in% c("1 - Strongly Disagree", "2 - Disagree") ~ "Disagree/Strongly Disagree",
      TRUE ~ "Neutral"
    )
  ) %>% group_by(Role, GroupedResponse) %>%
  summarize(Percent = sum(Percent))
  # Summarize the percentages for the grouped responses
  
```

```{r}
column = 12
for(i in 1:length(family)){
    if(i == 1){
      df = family[[i]] 
      combined = ifelse(!is.na(df[[column]]), df[[column]], df[[column + 24]])
    }
    df = family[[i]]
    if(length(df) == 52){
      combined = c(combined, df[[column]])
    }
  
    if(length(df) == 26){
      combined = c(combined, df[[column - 2]])
    }  
    
  }
  
# Set factor levels to include all response options from 1 to 5
  likert <- factor(combined, levels = c('1 - Strongly Disagree', '1 - Muy en desacuerdo',  '3 - Neutral', '4 - Agree', '4 - Estar de acuerdo', '5 - Strongly Agree', '5 - Totalmente de acuerdo'))
  
  # Create a frequency table and convert to percentages
  freq_table <- table(likert)
  
  percent_table <- (freq_table / sum(freq_table)) * 100
  
  percent_table_grouped = c(percent_table[1] + percent_table[2], percent_table[3] , percent_table[4] + percent_table[5] + percent_table[6] + percent_table[7])
  
  print(percent_table_grouped)
```

```{r}
response = c('Disagree/Strongly Disagree', 'Neutral', 'Agree/Strongly Agree')
role = rep("Family", 3)
data_family = data.frame(Percent = c(as.numeric(percent_table_grouped)), GroupedResponse = response, Role = role)
data_family
```

```{r}
data_all = bind_rows(data_grouped, data_family)
data_all
```

```{r}
data_all$GroupedResponse <- factor(
  data_all$GroupedResponse,
  levels = c("Disagree/Strongly Disagree", "Neutral", "Agree/Strongly Agree")
)
```

```{r}
data_all$Role <- factor(
  data_all$Role,
  levels = c("Mentee", "Mentor", "Family")
)
```



```{r}
# png("Comparison_recommendation_session_all.png")
ggplot(data_all, aes(x = GroupedResponse, y = Percent, fill = Role)) +
  geom_bar(stat = "identity", position = position_dodge()) + ylim(0, 100) + 
  geom_text(
    aes(label = paste0(round(Percent, 1), "%")),
    position = position_dodge(width = 0.9),
    vjust = -0.5
  ) +
  labs(
    title = "Perceptions of Program Recommendations", # I enjoy my mentoring sessions/I enjoy my mentoring sessions/ \n My child enjoys their mentoring sessions
    x = "Response",
    y = "Percentage"
  ) +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2") # +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1))
# dev.off()
```

